config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :users, only: [:index, :show, :new, :create]
  resources :skills, only: [:index, :show, :new, :create] do
    get 'page/:page', :action => :index, :on => :collection
  end
  resources :endorsements, only: [:create, :destroy]

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post  "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  #  Association
  belongs_to :user
  belongs_to :user_skill
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  #  Association
  has_many :user_skills
  has_many :users, through: :user_skills

  #  Validation
  #  name
  validates(
    :name,
    presence: true,
    uniqueness: true,
    length: { maximum: 25 }
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  #  Association
  has_many :user_skills
  has_many :skills, through: :user_skills

  has_many :endorsements
  has_many :endorsed_skills, through: :endorsements, source: :user_skill

  #  attr_accessor
  attr_accessor :remember_token

  #  Scope
  default_scope -> { order(created_at: :asc) }

  #  before_save
  before_save { self.email = email.downcase }

  #  Validation
  #  username
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9]+\Z/
  validates(
            :username,
            presence: true,
            length: { maximum: 30 },
            format: { with: VALID_USERNAME_REGEX }
  )

  #  email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(
            :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
  )

  # User security
  has_secure_password
  validates(
    :password,
    presence: true,
    length: { minimum: 7 },
    allow_nil: true
  )

  # Return hash
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Return random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  # Association
  belongs_to :user
  belongs_to :skill
  has_many :endorsements
  has_many :endorsing_users, through: :endorsements, source: :user

  validates :user_id, :uniqueness => {:scope => :skill_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  private def logged_in_user
    unless logged_in?
      store_location
      # flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :logged_in_user
end

app/controllers/endorsements_controller.rb
class EndorsementsController < BaseController
  def create
    @endorsement = current_user.endorsements.build(user_skill_id: params[:user_skill_id])
    if @endorsement.save
      redirect_to :back
    else
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @endorsement = current_user.endorsements.find(params[:id])
    @endorsement.destroy
    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_back_or user
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/skills_controller.rb
class SkillsController < BaseController
  def index
    @skills = Skill.page(params[:page])
  end

  def show
    @skill = Skill.find(params[:id])
    @skill_users = @skill.users.page(params[:page])
  end

  def create
    #  Params :user_id passed from form in users/show with hidden_field_tag
    @user = User.find(params[:user_id])
    #  Check if skill name exist
    if Skill.find_by(name: params[:skill][:name]).nil?
      @skill = @user.skills.build(skill_params)
      if @skill.save
        @skill_user = UserSkill.create(
          user_id: @user.id,
          skill_id: @skill.id
        )
        if @skill_user.save
          redirect_to @user
        else
          redirect_to @user
        end
      else
        redirect_to @user
      end
    else
      skill_id = Skill.find_by(name: params[:skill][:name]).id
      @skill_user = UserSkill.create(
        user_id: @user.id,
        skill_id: skill_id
      )
      if @skill_user.save
        redirect_to @user
      else
        redirect_to @user
      end
    end
  end

  def destroy
  end

  private
   def skill_params
     params.require(:skill).permit(:name, users_attributes: [:name])
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: :show

  def index
    @users = User.page(params[:page])
  end

  def show
    @user_skills = @user.skills
    @skill = @user.skills.build
    @endorsement = Endorsement.new unless current_user == @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_path @user
    else
      render 'new'
    end
  end

  private def set_user
    @user = User.find params[:id]
  end

  private def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :logged_in_root_view

  def index
    @user = User.new
  end

  private def logged_in_root_view
    if current_user != nil
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirect to store_location or default
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Remember URL which user want to visit
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %i.fa.fa-bars
      = link_to "SkillBank", root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - unless logged_in?
          %li
            = link_to "Sign up", signup_path
          %li
            = link_to "Login", login_path
        - else
          %li
            = link_to "All users", users_path
          %li
            = link_to "All Skills", skills_path
          %li
            = link_to "Profile", user_path(current_user)
          %li
            = link_to "Logout", logout_path, :method => :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0", :name => "viewport"}
    %title Skillbank
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/navbar"
    = yield
    = render "layouts/footer"

app/views/skills/index.html.haml
%section
  .container
    .row
      .col-lg-12
        %h1 All Skills
        = page_entries_info @skills
        %table.table
          %thead
            %tr
              %th Name
              %th Action
          %tbody
            - @skills.each do |skill|
              %tr
                %td= skill.name
                %td
                  = link_to "Show", skill_path(skill), class: "btn btn-info btn-sm"
        = paginate @skills

app/views/skills/show.html.haml
%section.bg-navy
  .container
    .row
      .col-lg-12
        %h1= @skill.name
%section.bg-teal
  .container
    .row
      .col-lg-12
        %h2 Who have this skill
      .col-lg-12
        = page_entries_info @skill_users
        %table.table.table-bordered.table-responsive
          %thead
            %tr
              %th Name
              %th Action
          %tbody
            - @skill_users.each do |user|
              %tr
                %td= user.username
                %th= link_to "Profile", user_path(user), class: "btn btn-default"
        = paginate @skill_users

app/views/users/index.html.haml
%section.bg-dark
  .container
    .row
      .col-lg-12
        %h1 All Users
        = page_entries_info @users
        %table.table
          %thead
            %tr
              %th Username
              %th Skill Count
              %th Action
          %tbody
            - @users.each do |user|
              %tr
                %td= user.username
                %td= user.skills.count
                %td
                  = link_to "Show", user_path(user), class: "btn btn-info btn-sm"
        = paginate @users

app/views/users/new.html.haml
%section
  .container
    .row
      .col-lg-12
        %h1 Sign up
        = form_for @user do |f|
          .form-group
            = f.text_field :username, class: "form-control", placeholder: :username, required: ""
          .form-group
            = f.email_field :email, class: "form-control", placeholder: :email, required: ""
          .form-group
            = f.password_field :password, class: "form-control", placeholder: :password, required: ""
          .form-group
            = f.password_field :password_confirmation, class: "form-control", placeholder: :password_confirmation, required: ""
          .form-group
            = f.submit "Register", class: "btn btn-primary"
        %p
          %small Already have an account?
        = link_to "Log in", login_path

app/views/users/show.html.haml
%header
  .container
    .row
      .col-lg-12
        %img.img-responsive{:alt => "", :src => "https://placeholdit.imgix.net/~text?txtsize=33&txt=200%C3%97200&w=200&h=200"}/
        .intro-text
          %span.username= @user.username
          %hr
          - @total_endorsement_count = 0
          - @user_skills.each do |skill|
            - unless skill.id == nil
              - @user_skill_id = UserSkill.where(user_id: @user.id, skill_id: skill.id).ids.first
              - @total_endorsement_count = @total_endorsement_count + Endorsement.where(user_skill_id: @user_skill_id).count
          %span.skills= "#{pluralize(@user.skills.count, "skill")} | #{pluralize(@total_endorsement_count, "endorsement")}"
%section.bg-warning.pd-b-xl
  .container
    .row
      .col-lg-12
        %h1= "#{@user.username}'s Skills"
        - if @user_skills.count < 1
          %h3 No Data... Add skill!
        - else
          %table.table
            %thead
              %tr
                %th Name
                %th Count
                - if current_user != nil
                  - unless current_user == @user
                    %th Action
            %tbody
              - @user_skills.each do |skill|
                - unless skill.id == nil
                  %tr
                    %td= link_to skill.name, skill_path(skill)
                    - @user_skill_id = UserSkill.where(user_id: @user.id, skill_id: skill.id).ids.first
                    %td
                      %button.btn.btn-info.btn-xs{"data-target" => "#m#{@user_skill_id}", "data-toggle" => "modal", :type => "button"} Endorsed by
                      = "#{pluralize(Endorsement.where(user_skill_id: @user_skill_id).count, "person")}"
                      %div{id: "m#{@user_skill_id}", class: "modal fade", role: "dialog"}
                        .modal-dialog
                          .modal-content
                            .modal-header
                              %button.close{"data-dismiss" => "modal", :type => "button"} ×
                              %h4.modal-title Endorsed by...
                            .modal-body
                              - Endorsement.includes(:user).where(user_skill_id: @user_skill_id).each do |ids|
                                %p= ids.user.username
                            .modal-footer
                              %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
                    -# - Endorsement.where(user_skill_id: @user_skill_id).each do |ids|
                    -#   %td= User.find(ids.user_id).username
                    - if current_user != nil
                      - unless current_user == @user
                        %td
                          - if current_user.endorsed_skills.where(user_id: @user.id, skill_id: skill.id) == []
                            = form_for @endorsement do |f|
                              = hidden_field_tag :user_skill_id, @user_skill_id
                              = f.submit "Endorse", class: "btn btn-primary"
                          - else
                            - @endorsement_id = Endorsement.find_by(user_id: current_user.id, user_skill_id: @user_skill_id).id
                            = link_to "REMOVE", endorsement_path(@endorsement_id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
- if current_user != nil
  %section
    .container
      .row
        .col-lg-12
          %h1 Add Skill
          = form_for @skill do |f|
            .form-group
              = f.text_field :name, class: "form-control", placeholder: "Skill name", required: ""
              = hidden_field_tag :user_id, @user.id
              = f.submit "Add Skill", class: "btn btn-primary"

app/views/welcome/index.html.haml
%section#top.full-bg#signuplogin.signup
  .full-bg-content
    .full-bg-content-inner
      .container
        .row
          .col-sm-5
            .form-box
              .form-top
                .form-top-left
                  %h3 I have an account
              .form-bottom
                = form_for (:session), url: login_path, html: { role: 'form', class:"form-horizontal" } do |f|
                  .form-group
                    = f.label :email
                    = f.email_field :email, class: "form-control", required: true
                  .form-group
                    = f.label :password
                    = f.password_field :password, class: "form-control", required: true
                  .form-group
                    = f.submit "Log in", class: "btn"
            -# .social-login
            -#   %p Use SNS
            -#   .social-login-buttons
            -#     %a.btn.btn-link-1.btn-link-1-facebook{:href => "#"}
            -#       %i.fa.fa-facebook
            -#       Facebook
            -#     %a.btn.btn-link-1.btn-link-1-twitter{:href => "#"}
            -#       %i.fa.fa-twitter
            -#       Twitter
            -#     %a.btn.btn-link-1.btn-link-1-google-plus{:href => "#"}
            -#       %i.fa.fa-google-plus
            -#       Google Plus
          .col-sm-1.middle-border
          .col-sm-1
          .col-sm-5
            .form-box
              .form-top
                .form-top-left
                  %h3 SignUp!
              .form-bottom
                = form_for @user, html: { role: "form", class: "form-horizontal"} do |f|
                  .form-group
                    = f.label :username
                    = f.text_field :username, class: "form-control", required: true
                  .form-group
                    = f.label :email
                    = f.email_field :email, class: "form-control", required: true
                  .form-group
                    = f.label :password
                    = f.password_field :password, class: "form-control", required: true
                  .form-group
                    = f.submit "Sign up", class: "btn"
                -# %form.registration-form{:action => "", :method => "post", :role => "form"}
                -#   .form-group
                -#     %label.sr-only{:for => "form-first-name"} First name
                -#     %input#form-first-name.form-first-name.form-control{:name => "form-first-name", :placeholder => "First name", :type => "text"}/
                -#   .form-group
                -#     %label.sr-only{:for => "form-last-name"} Last name
                -#     %input#form-last-name.form-last-name.form-control{:name => "form-last-name", :placeholder => "Last name", :type => "text"}/
                -#   .form-group
                -#     %label.sr-only{:for => "form-username"} Username
                -#     %input#form-last-name.form-last-name.form-control{:name => "form-username", :placeholder => "Username", :type => "text"}/
                -#   .form-group
                -#     %label.sr-only{:for => "form-department"} 学科
                -#     %input#form-last-name.form-last-name.form-control{:name => "form-department", :placeholder => "学科", :type => "text"}/
                -#   .form-group
                -#     %label.sr-only{:for => "form-email"} Email
                -#     %input#form-email.form-email.form-control{:name => "form-email", :placeholder => "Email", :type => "text"}/
                -#   %button.btn{:type => "submit"} 登録する!